# Generated by Django 4.2.6 on 2023-10-13 18:27

from django.db import migrations, models
import djapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=200, validators=[djapp.models.validate_check], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=200, validators=[djapp.models.validate_check], verbose_name='Фамилия'),
        ),
    ]
