# Generated by Django 4.2.6 on 2023-10-22 12:41

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_alter_worker_first_name_alter_worker_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField(unique=True, verbose_name='Пост')),
                ('user_id', models.BigIntegerField(verbose_name='Пользователь')),
                ('value', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Значение рейтинга')),
            ],
            options={
                'verbose_name': 'Отметка рейтинга',
                'verbose_name_plural': 'Отметки рейтинга',
                'ordering': ('post_id', 'user_id'),
            },
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('iin',), 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
