# Generated by Django 4.2.6 on 2023-10-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_news_rating_alter_worker_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
    ]
