# Generated by Django 4.2.6 on 2023-10-25 16:02

from django.db import migrations, models
import djapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_remove_worker_betteriin_alter_worker_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=200, validators=[djapp.models.validate_check, djapp.models.validate_symbols], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=200, validators=[djapp.models.validate_symbols], verbose_name='Фамилия'),
        ),
    ]
